version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: cins-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  fastapi-cins-app:
    build: .
    container_name: cins-fastapi-app
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
    ports:
      - "8002:8002"
    depends_on:
      - db

volumes:
  mysql_data:
